print("Make a eye for this robot")
eye = input()


print("         O")
print("         |")
print("     #########")
print("     #", eye," ", eye, "#")
print("     #  ___  #")
print("     #########")
print(" ##################")
print(" #  ##        #   #")
print(" #  ##        #   #")
print(" ##################")
print("     ##########")
print("     #   ##   #")
print("     #   ##   #")
print("     ##########")