print("         O")
print("         |")
print("     #########")
print("     # 0   0 #")
print("     #  ___  #")
print("     #########")
print(" ##################")
print(" #  ##        #   #")
print(" #  ##        #   #")
print(" ##################")
print("     ##########")
print("     #   ##   #")
print("     #   ##   #")
print("     ##########")